### ISSUE TITLE
GLib-GIO-ERROR **: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by tyrcho** [jberrenberg/docker-davmail#2]
When I connect from Thunderbird to the imap port 1143 exposed by davmail, I get this error ... anyone already faced this issue ?

docker build went fine

I'm starting the container with 

    docker run --rm -p 1143:1143 -v /home/mdaviot/dav/docker-davmail/davmail.properties:/etc/davmail/davmail.properties davmail

**Comment by maresb** [comment]
I recently ran into this problem.  The application I was trying to run (monodevelop) was looking for `/usr/share/glib-2.0/schemas/gschemas.compiled`.  A quick workaround was to copy the corresponding file from the host to the same location in the container, or simply to add `-v /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled:ro`
